os: 
  - osx

language: generic
osx_image: xcode9.2
script:
  - xcodebuild -showsdks
  - xcodebuild -scheme TABSwiftLayout -configuration Debug -sdk iphonesimulator11.0 -destination "OS=11.0,name=iPhone 6s Plus"